language: android
jdk: oraclejdk7
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ANDROID_BUILD_TOOLS_VERSION=22.0.1
    - API_LEVEL=22
android:
    components:
        # Uncomment the lines below if you want to
        # use the latest revision of Android SDK Tools
        # - platform-tools
        # - tools

        # The BuildTools version used by your project
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION

        # The SDK version used to compile your project
        - android-$API_LEVEL

        # Additional components
        # - extra-google-google_play_services
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-$API_LEVEL

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        # - sys-img-armeabi-v7a-android-19
        # - sys-img-x86-android-17
        # - sys-img-armeabi-v7a-android-$ANDROID_BUILD_TOOLS_VERSION
        - sys-img-armeabi-v7a-addon-google_apis-google-$API_LEVEL
        
before_install:
    - chmod +x gradlew
    # Create and start emulator
    - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"$API_LEVEL --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - adb wait-for-device
    - adb shell input keyevent 82 &
    
script: ./gradlew connectedAndroidTest

after_success:
    - mv ./app/build/outputs/apk/app-debug.apk ./app/build/outputs/apk/DroidEggs-debug.apk
    - ls ./app/build/outputs/apk/

deploy:
    provider: releases
    api_key: $OAUTH_KEY
    file: ./app/build/outputs/apk/DroidEggs-debug.apk
    skip_cleanup: true
    on:
        tags: true
