[versions]
activityCompose = "1.10.1"
agp = "8.11.1"
appcompat = "1.7.1"
appupdater = "4.0.1"
attribouter = "0.1.9"
composeBom = "2025.07.00"
coreKtx = "1.16.0"
dynamicanimationKtx = "1.1.0"
espressoCore = "3.7.0"
firebaseBom = "33.16.0"
firebaseCrashlytics = "3.0.5"
firebasePerf = "2.0.0"
flexbox = "3.0.0"
foundationAndroid = "1.10.0"
googleServices = "4.4.3"
helperlib = "1.6.4"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.0"
legacySupportV4 = "1.0.0"
material = "1.12.0"
multidex = "2.0.1"
preferenceKtx = "1.2.1"
sonarqube = "6.2.0.5505"
testCore = "1.7.0"
testRules = "1.6.1"
testRunner = "1.7.0"
uiToolingPreviewAndroid = "1.8.3"
window = "1.4.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-animation-core-android = { module = "androidx.compose.animation:animation-core-android" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-dynamicanimation-ktx = { module = "androidx.dynamicanimation:dynamicanimation-ktx", version.ref = "dynamicanimationKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-foundation-android = { module = "androidx.compose.foundation:foundation-android", version.ref = "foundationAndroid" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "testCore" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-ui-graphics-android = { module = "androidx.compose.ui:ui-graphics-android" }
androidx-ui-tooling-preview-android = { module = "androidx.compose.ui:ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
appupdater = { module = "com.itachi1706.appupdater:appupdater", version.ref = "appupdater" }
helperlib = { module = "com.itachi1706.helpers:helperlib", version.ref = "helperlib" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
attribouter = { module = "me.jfenn:Attribouter", version.ref = "attribouter" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
firebase = ["firebase-analytics", "firebase-crashlytics", "firebase-perf"]
